---
title: "Notebook"
name: Shubham Gaur
author: "Shubham Gaur"
date: "16/04/2020"
---

---

<p style="text-align:justify;"> 
  This Notebook is designed to maintain all the resources and learnings; which I have gained over my short period of studying/ Working. This notebook is totally dedicated to all the bits and pieces that made my life easier and took mo to the ride of exploring multiple technologies
</p>


# Introduction

<p style="text-align:justify;"> 
  I like to analyze data to answer research questions and test hypotheses. Currently I investigate questions related to security through my work as an Engineer at [Commscope Networks India Pvt. Ltd.](https://www.commscope.com) in the department of Networking and Information Technology.
</p>

<p style="text-align:justify;">
  I graduated from the [National Institute of Technology, Raipur](http://www.nitrr.ac.in/) with an Mtech in Information Technologys in 2019. In 2019 I started working as an Engineering Trainee at Commscope India, where I am investigatings methods to implement IP Security Services over cloud. Managing multiple docker containers over Kubernetes Engine. I am a security enthusiast, including serving on the board. My work involves Docker, Kubernetes, IPSec, Strongswan and Linux tools. 
</p>

My full CV is available [here](doc/resume.html).

---

## Technical Queries {.tabset .tabset-fade .tabset-pills}

### Windows

<p style="text-align:justify;">
    Firstly, boot from a UEFI Windows 8 recovery disk (CD/DVD/USB) − I found that the automated recovery process didn't find the correct Windows partition, nor when I managed to add it to BCD settings would it make it reliably bootable e.g. using BCDEDIT I got it to find and launch the Windows partition but it refused to cold boot or would not "keep" the settings after a 2nd reboot or power off.
<br>Go into the Advanced options and run the Command Prompt.Enter diskpart to use the DiskPart tool to ensure you have all the right partitions and to identify your EFI partition − the key thing here is that your EFI partition is formatted as FAT32:
</p>

```
DISKPART> sel disk 0
DISKPART> list vol
```

| Volume | Ltr | Label | Fs Type | Size | Status | Info |
|:---|:---:|:---|:---|:---|:---|:---:|
| Volume 0 | E | DVD-ROM |  | 0 B | No | Media |
| Volume 1 | C |  | NTFS Partition | 195 B | Healthy | Boot |
| Volume 2 | WINRE |  | NTFS Partition | 400 MB | Healthy | Hidden |
| Volume 3 |  |  | FAT32 Partition | 260 MB | Healthy | System |

```
Then assign a drive letter to the EFI partition:

DISKPART> sel vol 3
Volume 3 is the selected volume.

DISKPART> assign letter=b:
DiskPart successfully assigned the drive letter or mount point.
```

Exit DiskPart tool by entering exit and at the command prompt run the following:
```
cd ƒd b:\EFI\Microsoft\Boot\
bootrec ƒfixboot
```

Delete or rename the BCD file:
```
ren BCD BCD.bak
```

Use bcdboot.exe to recreate BCD store:
```
bcdboot c:\Windows ƒl en−gb ƒs b: ƒf ALL
```

The ƒf ALL parameter updates the BIOS settings including UEFI firmwareƒNVRAM, ƒl en−gb is to localise for UKƒGB locale. The localisation defaults to US English, or use en−US. Reboot and cross your fingers.

*This gave me headaches. I was going in circles for a long while. There isn't a lot of reliable info about fixing UEFIƒWindows 8 at the time of writing.*

To re−enable Hyper−V, I also had to run the following from an Administrator Command Prompt within Windows after rebooting:
```
bcdedit ƒset {default} hypervisorlaunchtype Auto bcdedit ƒset {default} nx OptIn
```

---

### Linux

#### Add on

```
LS_COLORS="ow=01;36;40" && export LS_COLORS
export DISPLAY=:0
PROMPT_DIRTRIM=2
```

#### Update and install necessary packages apt−get update

```
$ apt−get install linux−image−$(uname −r|sed 's,[^−]*−[^−]*−,,') linux−headers−$(uname −r|sed 's,[^−]*−[^−]*−,,') dpkg −i linux−headers−4.3.0−kali1−common_4.3.3−5kali4_amd64.deb
dpkg −i linux−headers−4.3.0−kali1−amd64_4.3.3−5kali4_amd64.deb
```

#### Install broadcom drivers

```
$ apt−get install broadcom−sta−dkms
Output:
```

#### Enable modules and disabled unnecessary ones

```
modprobe −r b44 b43 b43legacy ssb brcmsmac bcma modprobe wl
$ echo "Don't forget to enable network−manager: nano /etc/NetworkManager/NetworkManager.conf to true and restart the service."
```

#### Nanorc

```
set tabsize 4 set boldtext
set constantshow set mouse
set smarthome set smooth
set titlecolor brightwhite,blue set statuscolor brightwhite,green set keycolor cyan
set functioncolor green
```

#### Spark Setup

1. Extract Spark Setup
```
tar −xf spark−2.1.1−bin−hadoop2.6.tgz
```

1. Create a link to spark installation:
```
sudo ln −s ~/spark−2.1.1−bin−hadoop2.6 /usr/local/spark
```

1. Edit bashrc by adding these lines::

```
# SPARK ENVIRONMENT VARIABLES START #
export SPARK_HOME=/usr/local/spark export PATH=$SPARK_HOMEƒbin:$PATH
# SPARK ENVIRONMENT VARIABLES END #

# SPARK ENVIRONMENT VARIABLES START #
export SPARK_HOME=/usr/local/spark export PATH=$SPARK_HOME/bin:$PATH
# SPARK ENVIRONMENT VARIABLES END #
```

---

### Git

```
Optional: sed -i 's/\r$//' filename

git pull <branch>
git status
git clone user@ip://path

go get -u github.com/golang/protobuf/protoc-gen-go
export GOPATH=$PWD                                                     
export GOBIN=$PWD/bin                                                  
export CGO_ENABLED=0
export PATH=$PATH:$PWD/bin/
protoc -I proto/ proto/ipsec.proto --go_out=plugins=grpc:src/proto

// Only add: git add .
// Add and Commit: git commit -am "message"
git merge --squash <branch>
git merge branch
git rebase master
git reset --hard origin/master

If you execute git branch --all within a Git repository, remote tracking branches appear in red. These are read-only copies of the code as it appears on the remote.
git branch --all
git pull is a combination command, equal to git fetch + git merge

https://medium.com/@shakib37/how-to-install-golang-f8cbe15baa7c

Additional Information:
It’s worth noting that it is possible to maintain current local commits by creating a branch from master or whichever branch you want to work on before resetting:

For Example:

git checkout master
git branch new-branch-to-save-current-commits
git fetch --all
git reset --hard origin/master
git rm -r --cached  configs/configmap.json

git merge --squash develop
git rm --cached docs/*md
git commit --amend
git rebase --root -i
git push --force-with-lease origin master
"terminal.integrated.shell.windows": "C:\\windows\\System32\\wsl.exe",
"go.gopath": "/mnt/c/Users/SG1137/Documents/Projects/Ipsec",
"window.zoomLevel": 0,
"go.toolsGopath": "/home/sg1137/go",
"go.formatTool": "goimports",
"go.useLanguageServer": true,
"extensions.ignoreRecommendations": false,
"workbench.colorTheme": "Dobri Next -C06- Ayu",
"editor.fontFamily": "'Consolas', 'Courier New', monospace",
"markdown.extension.toc.githubCompatibility": true,
```

---

### Vimrc

```
" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Vim will load $VIMRUNTIME/defaults.vim if the user does not have a vimrc.
" This happens after /etc/vim/vimrc(.local) are loaded, so it will override
" any settings in these files.
" If you don't want that to happen, uncomment the below line to prevent
" defaults.vim from being loaded.
" let g:skip_defaults_vim = 1

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
" set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd            " Show (partial) command in status line.
"set showmatch          " Show matching brackets.
"set ignorecase         " Do case insensitive matching
"set smartcase          " Do smart case matching
"set incsearch          " Incremental search
"set autowrite          " Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a            " Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

:map <F2> :!ls<CR>:e
:nnoremap <C-I><C-I><C-I> <C-W><C-W>
:nnoremap <C-I><C-I> <C-t>
:nnoremap <C-I> <C-]>
:set tabstop=4
:set softtabstop=4
:set number
:set foldenable
:set foldlevelstart=10
:set foldnestmax=10
:set showcmd
:set wildmenu
:set lazyredraw
:set showmatch
:set incsearch
:set hlsearch
:set shiftwidth=4
:set expandtab
:set guifont=Consolas:h10.5
:colorscheme industry
:syntax enable
:nnoremap <leader><space> :nohlsearch<CR>

"highlight Normal term=none cterm=none ctermfg=White ctermbg=Black gui=none guifg=White guibg=Black
highlight DiffAdd cterm=none ctermfg=bg ctermbg=Green gui=none guifg=bg guibg=Green
highlight DiffDelete cterm=none ctermfg=bg ctermbg=Red gui=none guifg=bg guibg=Red
highlight DiffChange cterm=none ctermfg=bg ctermbg=Yellow gui=none guifg=bg guibg=Yellow
highlight DiffText cterm=none ctermfg=bg ctermbg=Magenta gui=none guifg=bg guibg=Magenta
```

---

### Bashrc
```
# ~/.bashrc: executed by bash(1) for non-login bashs.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything

case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(bash=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=no

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    #PS1='${debian_chroot:+($debian_chroot)}\[\033[00;97m\]\u@\h\[\033[01m\]:\[\033[00;91m\]\w\[\033[00;98m\]\$ '
    PS1='${debian_chroot:+($debian_chroot)}\[\033[00;90m\]\w\[\033[00;98m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b  ~/.dircolors)" || eval "$(dircolors -b )"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Add on
LS_COLORS="ow=00;96;80" && export LS_COLORS
#LS_COLORS=$LS_COLORS:'di=0;35:' && export LS_COLORS
export DISPLAY=:0
PROMPT_DIRTRIM=2
export GOROOT=/usr/local/go
export GOPATH=/home/kira/go:/mnt/s/Projects/GIT/IPSec
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:/home/kira/go/bin
cd /mnt/s
```

---

## Configurations {.tabset .tabset-fade .tabset-pills}

### Sublime

```
-----------------------------------------------------------
    SUBLIME
-----------------------------------------------------------
{
	"color_scheme": "Packages/ayu/ayu-dark.sublime-color-scheme",
	"font_face": "fira code retina",
	"font_size": 11,
	"ignored_packages":
	[
		"Vintage"
	],
	"theme": "ayu-dark.sublime-theme"
}

-----------------------------------------------------------
    PACKAGE: OUTLINE
-----------------------------------------------------------
{
	"outline_width": 0.1,
	"color_scheme": "Packages/ayu/ayu-dark.sublime-color-scheme",
  	"word_wrap": false,
  	"highlight_line": true,
  	"font_face": "times new roman",
    "font_size": 11,
}

-----------------------------------------------------------
    KEY BINDINGS
-----------------------------------------------------------
[
    // Toggle the default shell in panel
    { "keys": ["alt+`"], "command": "toggle_terminus_panel", "args": {
             "cwd": "${file_path:${folder}}"
         } 
    },
    // Open a terminal view at current file directory
    {
         "keys": ["ctrl+alt+t"], "command": "terminus_open", "args": {
             "cwd": "${file_path:${folder}}"
         }
    },
    { "keys": ["alt+m"], "command": "markdown_preview", "args": {"target": "chrome", "parser":"markdown"} }
]
```

### Terminus
```
-----------------------------------------------------------
    TERMINUS
-----------------------------------------------------------
{
	"256color": true,
	"debug": false,
	"natural_keyboard": true,
	"preserve_keys":
	[
	],
	"scrollback_history_size": 100000000,
	"shell_configs":
	[
		{
			"cmd": "bash.exe",
			"default": true,
			"enable": true,
			"env":
			{
			},
			"name": "Ubuntu",
			"platforms":
			[
				"windows"
			]
		},
		{
			"cmd": "cmd.exe",
			"default": false,
			"enable": true,
			"env":
			{
			},
			"name": "Command Prompt",
			"platforms":
			[
				"windows"
			]
		},
		{
			"cmd": "pwsh.exe",
			"default": false,
			"enable": true,
			"env":
			{
			},
			"name": "PowerShell Core",
			"platforms":
			[
				"windows"
			]
		},
		{
			"cmd": "powershell.exe",
			"default": false,
			"enable": true,
			"env":
			{
			},
			"name": "PowerShell",
			"platforms":
			[
				"windows"
			]
		},
		{
			"cmd": "wsl.exe",
			"default": false,
			"enable": true,
			"env":
			{
			},
			"name": "WSL Login Shell",
			"platforms":
			[
				"windows"
			]
		}
	],
	"theme": "argonaut",
	"unix_lang": "en_US.UTF-8",
	"unix_term": "linux",
	"view_settings":
	{
		"font_face": "ubuntu mono",
		"font_size": 11
	}
}
```

### Notes
```
-----------------------------------------------------------
    NOTES
-----------------------------------------------------------
// These settings override both User and Default settings for the notes syntax
{
    "font_face": "Times New Roman",
    "font_size": 11,
    "wrap_width": 80
}
```

### Markdown
```
-----------------------------------------------------------
    MARKDOWN
-----------------------------------------------------------
```

### Pandoc
```
-----------------------------------------------------------
    PANDOC
-----------------------------------------------------------
pandoc -V geometry:paperwidth=8.3in -V geometry:paperheight=11.70in -V geometry:margin=1.2in test.md -s -o demo.pdf --listings --latex-engine=xelatex --number-sections
pandoc -H block.pandoc -V geometry:a4paper -V geometry:margin=2cm test.md -s -o test.pdf --listings --latex-engine=xelatex --number-sections
```

### Latex
```
-----------------------------------------------------------
    LATEX
-----------------------------------------------------------
\lstset{
    basicstyle=\ttfamily,
    numbers=left,
    numberstyle=\footnotesize,
    stepnumber=2,
    numbersep=5pt,
    backgroundcolor=\color{black!10},
    showspaces=false,
    showstringspaces=false,
    showtabs=false,
    tabsize=2,
    captionpos=b,
    breaklines=true,
    breakatwhitespace=true,
    breakautoindent=true,
    linewidth=\textwidth
}

\lstset{
    basicstyle=\ttfamily,
    numbers=left,
    keywordstyle=\color[rgb]{0.13,0.29,0.53}\bfseries,
    stringstyle=\color[rgb]{0.31,0.60,0.02},
    commentstyle=\color[rgb]{0.56,0.35,0.01}\itshape,
    numberstyle=\footnotesize,
    stepnumber=1,
    numbersep=5pt,
    backgroundcolor=\color[RGB]{248,248,248},
    showspaces=false,
    showstringspaces=false,
    showtabs=false,
    tabsize=2,
    captionpos=b,
    breaklines=true,
    breakatwhitespace=true,
    breakautoindent=true,
    escapeinside={\%*}{*)},
    linewidth=\textwidth,
    basewidth=0.5em,
}
```

### Pdf
```
-----------------------------------------------------------
    PDF
-----------------------------------------------------------
qpdf --linearize --encrypt "commscope@" "shubh2495@" 128 --print=none --modify=none --extract=n --use-aes=y -- ike.pdf IKE-SA.pdf
```

---

## List of Articles {.tabset .tabset-fade .tabset-pills}
### 2020
* <a target="_blank" rel="noopener noreferrer" href="doc/kubernetes.html">Kubernetes</a>

---

### 2019
* <a target="_blank" rel="noopener noreferrer" href="doc/ipsec.html">IPSec</a>

---

## References
*
*
*

---

<br />&nbsp;<br />&nbsp;<br />&nbsp;<br />
<center> <strong> Copyright </strong> </center>
<p style="text-align:center;"><a target="_blank" rel="noopener noreferrer" href="doc/copyright.html">Shubham Gaur. &copy; 2020 Commscope</a></p>

