---
name: "Shubham Gaur"
title: "COMMSCOPE © 2020"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    theme: flatly
---

| Liscensed By | COMMSCOPE-GPL |
| :--- | :--- |
| Guided By | **Sriram Dharwadkar** |
| Documented By | **Shubham Gaur** |
| Period | Aug 16,2019 :: Sep 13,2019 |
| Updated By | Sep 13,2019 |
| Designation | **Engineering Trainee** |
| Email | [Shubham.Gaur@commscope.com](www.outlook.com) |

### Copyright

This document and its content is copyright of [COMMSCOPE](https://www.commscope.com) - © [COMMSCOPE](https://www.commscope.com) 2019. All rights reserved.

<p style="text-align:justify;"> 
Any redistribution or reproduction of part or all of the contents in any form is prohibited other than the following:
* you may print or download to a local hard disk extracts for your personal and non-commercial use only.
* you may copy the content to individual third parties for their personal use, but only if you acknowledge the *author* and [*COMMSCOPE*](https://www.commscope.com) as the source of the material.
</p>

<p style="text-align:justify;"> 
**You may not, except with our express written permission, distribute or commercially exploit the content. Nor may you transmit it or store it in any other website or other form of electronic retrieval system.**
</p>