---
title: "Resume"
author: "Shubham Gaur"
date: "16/04/2020"
output: 
  html_document:
    df_print: paged
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    theme: flatly
    # “cerulean”, “cosmo”, “flatly”, “journal”, “lumen”, “paper”, “readable”, “sandstone”, “simplex”, “spacelab”, “united”, and “yeti”
    highlight: tango
---

## Education

### M. Tech. 
#### Information Techology [2017-19]
* National Institute of Technology (Raipur)
    -  Thesis: Secure Information Aggregation for Smart Grid
    -  CGPA: 8.25  

### B. Tech
#### Computer Science and Engineering [2013-17]
* Chameli Devi School of Engineering (Indore)
* Rajiv Gandhi Technical University (Bhopal)
    - Major: Intelligent Attendance Management System
    - CGPA: 7.95

### XII Std.  
* Govt. Excellence H. S. School (Sheopur) [2012-13]
* Madhya Pradesh Board of Secondary Education (MPBSE, Bhopal)
    - Percentage: 85.20%  

### X Std.  
* St. Pius School (Sheopur) [2010-11]
* Central Board of Secondary Education (CBSE)
    - Percentage: 85.20%  

## Experience / Training

### Commscope Networks India
Handling protocols, feature add-ons and bug fixes in networking domain

- Works as a network engineer
- Implementing security protocols and security associations in ipv4 and ipv6 domains

### National Institute of Technology

- Deep Learning: TensorFlow
- Apache Spark: Pyspark, ML, Pipeline
- Realization of research paper “Secure Information Aggregation for Smart Grids using Homomorphic Encryption” by Fengjun Li, Bo Luo, Peng Liu with the help of Paillier Encryption and Python 2.7.
- Omnet++, Matlab

### Zensar Techologies

- Trained in java core and advance.
- Trained in SQL/PLSQL.

### Open Courses

- Certification in Core Java

## Technical Skills
| Beginner | Intermediate | Advance |
| --- | --- | --- |
| MATLAB | C/C++ | |
| OMNET++ | Python 2.7 | |
| Tensorflow |  Java Core | |
| Apache Spark | Java Core | |
| PySpark | SQL | |
| ML | PLSQL | |
| Pipelines | HTML/CSS | |

## Projects
1. **Activity Recognition using Tensorflow [Nov 2018] :**
Determining human activity using positional coordinates. Classification using RELU and Softmax with an accuracy of 98.20%.
    - Tools : Tensorflow, Python 2.7
    -  Dataset : WISDM, Kaggle-UCI

1. **Human Activity Recognition using Apache Spark and ML [Aug 2018] :** 
Determining human activity using positional coordinates. Classifiers such as Logistic Regression, Decision Tree and Random Forest were used. Logistic regression was further tuned with cross fold giving an accuracy of 92%.
    - Tools : Apache Spark- PySpark, ML pipelines
    - Dataset : WISDM, Kaggle-UCI

1. **Secure Information Aggregation for “ Smart Grid ” [Dec 2017] :**
Developed a virtual Smart Grid System using tree structure and applied Homomorphic Encryption using Paillier Encryption to avoid intrusion with data on communication channels and thus enhancing security.
    - Tools : Python 2.7, CSV

1. **Intelligent Attendance Management System [Jan 2017] :**
Application software developed to automate the process of attendance marking system using face recognition.
    - Tools : Python2.7, Open CV 3.0, MySQL

1. **Home Cloud [Nov 2016] :**
Web application created to simplify sharing of data on local area network.
    - Tools : Java, Oracle SQL
    - Server : Apache Tomcat

1. **Billing Application [Oct 2016] :**
Application developed to simplify the process of bill generation with variable tax inclusion.
    - Tools : Java

### Programming Languages
* **Python :** jaej;
* **C/C++ :** Description of your experience with second-lang, perhaps again including a [link] [ref], this time placing the url reference elsewhere in the document to reduce clutter (see source file). 
* **JAVA:** We both know this one's pushing it.
* Basic knowledge of **Javascript**, **Rust**, **C#**

## Achievements
* Cleared Gate 2019 [Mar 2017]
    - Percentile : 93.98
* Rio+21 IYWC India Certificate Program [Oct 2014]
    - Grade: B

## Personals
* Permanent Residence: 62, Baroda Road, Sheopur (M.P.)
* DOB: July 22, 1995
* Human Languages:
     * English 
     * Hindi (native speaker)  

---